[package]
name = "picm"
version = "0.1.1"
authors = ["István Nagy <nistvan.86@gmail.com>"]
edition = "2018"

[dependencies]
videocore = { git = "https://github.com/ionosnetworks/rust-videocore" }
hound = "3.4.0"
claxon = "0.4.3"
clap = "3.0.0-beta.1"
rb = "0.3.2"
thread-priority = "0.2.0"
