[package]
name = "picm"
version = "0.1.0"
authors = ["István Nagy <nistvan.86@gmail.com>"]
edition = "2018"

[dependencies]
videocore = { git = "https://github.com/ionosnetworks/rust-videocore" }
hound = "3.4.0"
clap = "3.0.0-beta.1"
